global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['backend:3000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alert.rules.yml' 