# Fly.io Configuration for Exchange Platform Backend
app = "exchange-platform-backend"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["npm", "start"]

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
  [[http_service.checks]]
    grace_period = "5s"
    interval = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "3s"
    headers = {}

[[services]]
  internal_port = 3000
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "requests"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    port = 3000
    timeout = "3s"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "3s"
    headers = {}

[deploy]
  release_command = "echo 'Deployment starting...'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512