# kubernetes/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: exchange-system
  labels:
    name: exchange-system
---
# kubernetes/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-backend
  namespace: exchange-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exchange-backend
  template:
    metadata:
      labels:
        app: exchange-backend
    spec:
      containers:
      - name: backend
        image: your-registry/exchange-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: exchange-backend-service
  namespace: exchange-system
spec:
  selector:
    app: exchange-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
