openapi: 3.0.0
info:
  title: Financial & Discrepancy Reports API
  version: 1.0.0
  description: >
    API endpoints for financial reporting and discrepancy management in the multi-tenant exchange platform.
servers:
  - url: /api/reports
paths:
  /financial:
    get:
      summary: Get filtered financial report
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: from
          schema:
            type: string
            format: date
          description: Start date (YYYY-MM-DD)
        - in: query
          name: to
          schema:
            type: string
            format: date
          description: End date (YYYY-MM-DD)
        - in: query
          name: type
          schema:
            type: string
          description: Transaction type (e.g. payment, remittance)
        - in: query
          name: branchId
          schema:
            type: string
          description: Branch ID (optional)
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        total:
                          type: number
                        count:
                          type: integer
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /discrepancies:
    get:
      summary: Get discrepancy report for current tenant
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  discrepancies:
                    type: array
                    items:
                      type: object
                      properties:
                        tenantId:
                          type: string
                        branchId:
                          type: string
                        transactionId:
                          type: string
                        expected:
                          type: number
                        paid:
                          type: number
                        status:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 